### ISSUE TITLE
Change package name if its possible

### ISSUE THREAD

**Issue by spyp** [dwightwatson/aggregate#1]
Thanks to develop this i started something like this but its better if we develop your package
I suggest. if you can change the package name . because we can wrapper model features that doesn't in laravel core. if no we have to create many packages for each feature :)

**Comment by dwightwatson** [comment]
Thanks for the inspiration and I'm glad to hear you're on board!

My initial thought was to keep it focused on the aggregation functionality as it keeps dead simple, especially as it doesn't require any installation or configuration beyond the Composer install. Happy to consider taking it further if there were other things you had in mind - that might help point in the direction of a better name?

**Comment by spyp** [comment]
mmm let's see what happening in feature . I will create new package with some  tools that i think it's
useful in finance applications that need complex queries and one of them we solved with Aggregate
Hope will help . thanks.
